### PR TITLE
add option 'limitMin' and handle max/min-hit value

### LINKED ISSUE #109: gauge ark doesn't show properly when value is out of the range
see [jsfiddle](https://jsfiddle.net/hs5yfLqy/)

### PR DESCRIPTION
**Pull request by hangy233**
Hi,

I'm a little confused about [this line](https://github.com/bernii/gauge.js/blob/gh-pages/dist/gauge.coffee#L350) in gauge.coffee.
I guess this is causing issue #109. It seems increasing the maxValue when the pointer value hits the maxValue. (So the pointer never goes out of the gauge?)
Assuming this is true, I made some changes to fix #109 and add options "limitMin" (Shall we call them "fixMin/Max" instead of "limit"?)
Please check and let me know if I'm wrong.

Thanks

### CODE REVIEW

**Comment by kplindegaard** [comment]
I don't know the story behind the line you refer to, increasing the max value with 10% if the max value is exceeded. Be that as it may, but I am in favor of being able to not only have a limitMax but also a limitMin option as you suggest. To not mess up backwards compatibility, we should use the prefix "limit" and not "fix".

**Comment by hangy233** [comment]
Totally agreed. My code basically does the same thing.
I changed `@value` to  `val`, because `@value` is the previous gauge value (this is causing the issue I referred).
Increasing the max value with 10% is also potentially dangerous if there is any negative value. So I changed it to [`@maxValue = val + 1`](https://github.com/bernii/gauge.js/pull/110/files#diff-44ef763eed665af7846064cd9f2f697eR352)
Could you double check the code and merge the pull request if they looks OK to you?

**Comment by kplindegaard** [comment]
@johanye I started to play a bit with your fix in [this JSFiddle](https://jsfiddle.net/xeea6pr9/). It includes gauge.min.js from your gh-pages branch. 
However, I have some difficulties getting the limitMin-option to work properly. If I enable it, the gauge will not render at all.

**Comment by hangy233** [comment]
Thanks for pointing out @kplindegaard .
I think this is because the flag 'max_hit', It always executes ```AnimationUpdater.run();```
See https://github.com/bernii/gauge.js/blob/gh-pages/dist/gauge.js#L511-L533
I did it wrong in my code. Please try again at [your fiddle](https://jsfiddle.net/xeea6pr9/3/)

**Comment by kplindegaard** [comment]
@johanye: It's looking pretty good now, thanks for having a second go at it. 
I have modified [the original JSFiddle](https://jsfiddle.net/xeea6pr9/) a bit where the pointer now tries to exceed both the max and the min value before settling back in at the mean value 150. It looks very nice :+1: 

Sorry for messing up your pull request by merging in a variety of stuff and changes. Do you mind fetching from upstream and merge recent changes into your fork before resubmitting the pull request?

**Comment by hangy233** [comment]
The demo looks nice! Thanks for merging @kplindegaard!

**Pull request merged**
