### PR TITLE
Add support for static zones

### PR DESCRIPTION
**Pull request by rsreimer**
I have a customer who required static zones on the gauge as shown below:
gauge

I have added this feature and made it configurable with the `staticZones` option:

``` javascript
var gauge = new Gauge(canvas)
    .setOptions({
        staticZones: [
            {strokeStyle: "#30B32D", span: 2/3}, // Green
            {strokeStyle: "#FFDD00", span: 1/6}, // Yellow
            {strokeStyle: "#F03E3E", span: 1/6}  // Red
        ]});
```

The order of the array matters as the zones are added from left to right.
The sum of all spans should be 1.

### CODE REVIEW

**Comment by sondrele** [comment]
Awesome, was looking after the same thing.

+1 for this

**Comment by eblancart** [comment]
I was looking for that as well ! Perfect !

**Comment by bernii** [comment]
That's awesome. @rsreimer I've given you push access to the repo. Do you mind merging?

**Comment by kplindegaard** [comment]
@rsreimer: I was very inspired by what you had done and used your fork in a small project together with a couple of other modifications. The net result of that is in the recent commit 364a42b7efaad94bc36de9196155e12c69886074.

Unfortunately and due to my lack of GitHub skills this pull request is now redundant. I propose to close this. Sorry about that, but thanks a bunch and kudos to you for your contibution.

**Comment by kplindegaard** [comment]
@rsreimer I am closing your pull request. Sorry that I messed up. Your code still lives on, though :+1:

**Pull request closed without merging**
