### PR TITLE
Add gauge flexibility

### PR DESCRIPTION
**Pull request by Knight2601**
added height option to `staticZones`
this offsets and expands the line style for this segment

added font size override per `staticLabels` object, optional label override to {label: 'label value', font: 'font string'} or just straight value as existing.

example
```
    var bigFont = "15px sans-serif";
    var opts = {
      angle: 0.1,
      radiusScale:0.9,
      lineWidth: 0.2,
      pointer: {
        length: 0.6,
        strokeWidth: 0.05,
        color: '#000000'
      },
      staticLabels: {
        font: "10px sans-serif",
        labels: [{label:200, font: bigFont}, 
        {label:750}, 
        {label:1500}, 
        {label:2250}, 
        {label:3000, font: bigFont}],
        fractionDigits: 0
      },
      staticZones: [
        {strokeStyle: "rgb(255,0,0)", min: 0, max: 500, height: 1.4},
        {strokeStyle: "rgb(200,100,0)", min: 500, max: 1000, height: 1.2},
        {strokeStyle: "rgb(150,150,0)", min: 1000, max: 1500, height: 1},
        {strokeStyle: "rgb(100,200,0)", min: 1500, max: 2000, height: 0.8},
        {strokeStyle: "rgb(0,255,0)", min: 2000, max: 3000, height: 0.6},
        {strokeStyle: "rgb(80,80,80)", min: 2470, max: 2530, height: 1.3}        
      ],
      limitMax: false,
      limitMin: false,
      highDpiSupport: true
    };
```

### CODE REVIEW

**Comment by kplindegaard** [comment]
Awesome! Unfortunately a bit busy these days, but I will have a look as soon as I can. 

Sorry for asking perhaps silly questions without a proper look at what you have done yet, but:
1. Have you considered backwards compatibility? Can't afford to break current staticLabels.
1. Is it necessary to have node_modules there? Personally I like to have the repos as clean as a possible.
1. Would you like to become a contributor to gauge.js yourself?

**Comment by Knight2601** [comment]
Hi, yes it is backward compatible, it has a simple check to see if the labels object has properties (value.label) otherwise falls through to operate in the old way, theres a simple example on the index page using the same system, it worked for me on all the same browsers in browserstack, so should be good. Also fixed the coffee as there were no calls to super() before init’ing this.

No the node mods aren’t necessary, but being new to coffee, it took me a while to get it running so figure I’d save the next guy the hassle… ☺

And yeah I don’t mind being listed as a contrib, I had to expand the functionality as it was a bit limited as it was – and probably will have a need to do more.

I quite liked producing stuff like this :
g1
[cid:image003.jpg@01D3625D.97151C20]

They’re just a little more fun to look at ☺
g2


[cid:image004.jpg@01D3625D.97151C20]
Many thanks

Andy

**Comment by kplindegaard** [comment]
Hello. Sorry for slow response.

The image links are cool!

I appreciate the idea of making things simpler for developers, but it's just that I don't really fancy adding unnecessary developer dependencies like this. To me one of the nice things about this project is that it is so small from the start. 

Here's what I suggest:
* Remove the node_modules folder.
* Remove build.ps1 (Powershell, right?) I have no idea about those things. Alternatively supply a bash-script equivalent.
* Revert the coffeescript devDependency in package.json. Unfortunately I don't think we should risk annoying some gauge.js users by all of a sudden also making them download coffee.

Looking forward to get this PR and #153 merged and released :)

**Review by kplindegaard — APPROVED** [review]
Lovely. Thank you.

**Comment by Knight2601** [comment]
might be worth updating the documentation to reflect the addition a little better?

**Comment by kplindegaard** [comment]
Agree.
BTW I have asked Berni to add you as contributor.
Update: Collaborator is the correct term.

**Comment by kplindegaard** [comment]
I just discovered a small artifact I didn't see before. If you open http://bernii.github.io/gauge.js/ you will see that something is painted in the upper left corner while the gauge pointer is moving. Try e.g. to play with the Current Val slider.
Don't think it was there before, because my fork (https://kplindegaard.github.io/gauge.js/) does not have it. Perhaps you know what the issue might be?

**Comment by Knight2601** [comment]
Yeah, weird, it looks like an erroneous pointer draw when you click between the example thumbnails, I’ll have a look.

**Comment by bernii** [comment]
@Knight2601 thanks for your really cool PRs - adding you as `collabolator` to the repo.

**Comment by Knight2601** [comment]
Thank you ☺ great utility though!!

**Comment by Knight2601** [comment]
Ok all fixed

See #153 (version incremented too) + live ticks example

**Comment by Knight2601** [comment]
Fixed and updated pr#153 with live examples of ticks on all Gauge types. Incremented version to 1.3.6 to add in scalable sections and ticks.

Tried resolving the conflicts but it says I don’t have write access to the repo – so can’t.

If you just select my changes in each file, it’ll be good.

Thanks

**Comment by Knight2601** [comment]
Yay, ok so I could resolve conflicts, the whole shebang is sitting on PR #153, please review proposed changes.

**Pull request merged**
